return {
    -- "epwalsh/obsidian.nvim",
    -- lazy = true,
    -- enabled = true,
    -- event = {
    --     -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
    --     -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/**.md"
    --     "BufReadPre "
    --         .. vim.fn.expand("~")
    --         .. "/Library/Mobile Documents/iCloud~md~obsidian/Documents/CheatSheet/**.md",
    --     "BufNewFile "
    --         .. vim.fn.expand("~")
    --         .. "/Library/Mobile Documents/iCloud~md~obsidian/Documents/CheatSheet/**.md",
    -- },
    -- dependencies = {
    --     -- Required.
    --     "nvim-lua/plenary.nvim",
    --     -- see below for full list of optional dependencies 👇
    -- },
    -- opts = {
    --     dir = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/CheatSheet", -- no need to call 'vim.fn.expand' here
    --     notes_subdir = "001Inbox",
    --     daily_notes = {
    --         folder = "002Diary",
    --         date_format = "%Y-%m-%d",
    --         template = "902Template/DiaryTemplate.md",
    --     },
    --     overwrite_mappings = true,
    --     -- see below for full list of options 👇
    -- },
    -- keys = function()
    --     return {
    --         {
    --             "<leader>of",
    --             "<cmd>ObsidianFollowLink<cr>",
    --             desc = "go to link",
    --         },
    --         {
    --             "<leader>os",
    --             "<cmd>ObsidianSearch<cr>",
    --             desc = "search",
    --         },
    --         {
    --             "<leader>ob",
    --             "<cmd>ObsidianBacklinks<cr>",
    --             desc = "show backlinks",
    --         },
    --         {
    --             "<leader>ot",
    --             "<cmd>ObsidianTemplate<cr>",
    --             desc = "insert template",
    --         },
    --     }
    -- end,
}
-- /Users/xiaobai/Library/Mobile Documents/iCloud~md~obsidian/Documents/CheatSheet
